version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pismo_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pismo_db
    ports:
      - "3306:3306"
    volumes:
      - pismo_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pismo_network

# persist mysql to /var/lib/mysql
volumes:
  pismo_data:

# define network so mysql can communicate with service
networks:
  pismo_network:
